services:
  - type: web
    name: quiz-api
    env: node
    rootDir: api
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: MONGO_URI
        fromDatabase: YOUR_DB_CONNECTION_NAME
      - key: JWT_SECRET
        value: your_jwt_secret_here